version: '3.8'

services:
  # El Sistema Nervioso Central (MQTT)
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: orion_mqtt
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/data:/mosquitto/data
      - ./docker/mosquitto/log:/mosquitto/log

  # NÃºcleo Operativo (Brain)
  orion-brain:
    build:
      context: .
      dockerfile: ./docker/brain.Dockerfile
    container_name: orion_brain
    restart: always
    privileged: true
    network_mode: host
    depends_on:
      - mqtt-broker
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    environment:
      - MQTT_HOST=localhost
      -PYTHONPATH=/app